
def flash_ver():
      return 'WIN\\2021,0,0,242'

def get_shockwave():
      return 'ShockwaveFlash/21.0.0.242'
      
def blacklist():
      black = ['advert', 'banner', 'bet', 'c4.zedo', 'chat', 'chatango', '.css', 'histats']


resolver_dict={ 'sawlive.tv': 'sawlive',
            'streamking.co': 'streamking',
            'streamking.cc': 'streamking',
            'castalba.tv' : 'castalba',
            'p2pcast.tv' : 'p2pcast',
            'p2pcast.tech' : 'p2pcast',
            'finecast.tv' : 'finecast',
            'filmon.com' : 'filmon',
            'miplayer.net' : 'miplayer',
            'lshstreams.com' : 'lshunter',
            'cdn.lshstream.com' : 'lshunter',
            'castamp.com' : 'castamp',
            'yocast.tv': 'yocast',
            'streamlive.to' : 'streamlive',
            '04stream.com' : 'o4stream',
            'ustream.tv' : 'ustream' ,
            'playwire.com' : 'playwire',
            'leton.tv' : 'leton',
            'yotv.co' : 'yotv',
            'hdcast.me' : 'hdcast',
            'zerocast.tv' : 'zerocast',
            'castup.tv' : 'castup',
            'mybeststream.xyz' :'mybeststream',
            'sunhd.info' : 'dinozap',
            'ponlatv.com' : 'dinozap',
            'youtube.com' : 'youtube',
            'livestream.com' : 'livestream',
            'new.livestream.com' : 'livestream',
            'privatestream.tv' : 'privatestream',
            'airq.tv' : 'airq',
            'aliez.me' : 'aliez',
            'emb.aliez.me' : 'aliez',
            'emb.aliez.tv' : 'aliez',
            'p3g.tv' : 'p3g',
            'liveflashplayer.net' : 'liveflashplayer',
            'laola1.tv' : 'laola1',
            'ehftv.com' : 'laola1',
            'zoomtv.me' : 'zoomtv',#not implemented
            'iguide.to' : 'iguide',
            'letgo.tv' : 'letgo',
            'streamup.com' : 'streamup',
            'cast3d.tv' : 'cast3d',
            'xvtr.pw' : 'dinozap',
            'turbocast.tv' : 'turbocast', #not implemented
            'direct-stream.org' : 'directstream',
            'pxstream.tv' : 'pxstream',
            'pushpublish.tv' : 'publishpublish',
            'embeducaster.com' : 'mips',
            'rocktv.co' : 'rocktv',
            'embedezcast.com' : 'ezcast',
            'micast.tv' : 'micast',
            'openlive.org' : 'openlive',
            'sostart.org' : 'sostart',
            'sostart.pw' : 'sostart2',
            'scity.tv' : 'sostart2',
            'hqstream.tv' : 'hqstream',
            'tutelehd.com' : 'tutele',
            'janjua.tv' : 'janjuaf',
            'abcast.net' : 'abcast',
            'castfree.me' : 'castfree',

            'playerapp1.pw' : 'dinozap',
            'playerapp2.pw' : 'dinozap',
            'playerhd1.pw' : 'dinozap',
            'playerhd2.pw' : 'dinozap',

            'dinostream.pw' : 'dinozap',
            'dinozap.info'  : 'dinozap',
            'tv.verdirectotv.org' : 'dinozap',
            'serverhd.eu' : 'dinozap',
            'sitenow.me' : 'dinozap',
            'sstream.pw' : 'dinozap',


            'streamcasttv.biz':'streamcasttv',
            'vaughnlive.tv' : 'vaughnlive',
            'vapers.tv' : 'vaughnlive',
            'breakers.tv' : 'vaughnlive',
            'instagib.tv' : 'vaughnlive',
            'hdcast.org' : 'hdcast_org',
            'ustream.tv' : 'ustream',
            'cast4u.tv' : 'cast4u',
            'youtu.be' : 'youtube',
            'direct-stream.org' : 'directstream',
            'veetle.com' : 'veetle',
            'tvope.com' : 'tvope',
            'static.castto.me' :  'castto',
            'castasap.pw' : 'castasap',
            'flashlive.pw' : 'castasap',
            'castflash.pw' : 'castasap',
            'fastflash.pw' : 'castasap',
            'deltatv.xyz' : 'deltatv',
            'deltatv.pw' : 'deltatv',
            'deltatv.site' : 'deltatv',
            'hdcast.info' : 'hdcastinfo',
            'theactionlive.com' : 'theactionlive',
            'ustvnow.com' : 'ustvnow',
            'hornos.moy.su' : 'kolstg',
            'mipsplayer.com' : 'mips',
            'bro.adcast.tech' : 'broadcast',
            'bro.adca.st' : 'broadcast',
            'sportstream365.com':'sportstream365',
            'navixsport.com' : 'navix',
            'cndhlsstream.pw' : 'cndhls',
            'streamifyplayer.com' : 'streamify',
            'zoptv.com' : 'zoptv',
            'streamp2p.com' : 'streamp2p',
            'akamaistreaming.com' : 'akamaistreaming',
            'cast3d.me' : 'dinozap'
              }
